import { DEFAULT_RF_INPUTS } from './rfPlanning';
import type { RfInputs } from './rfPlanning';

/** Illustrative planning inputs, not equipment specifications or regulatory limits. */
export const RF_PRESETS: readonly { id: string; label: string; note: string; values: RfInputs }[] =
  [
    {
      id: 'custom',
      label: 'Custom radio link',
      note: 'Set the values from your equipment specifications.',
      values: DEFAULT_RF_INPUTS,
    },
    {
      id: 'handheld',
      label: 'UHF handheld · 446 MHz',
      note: 'Example short-range handhelds, 0.5 W and 1.5 m antennas.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 446,
        transmitDbm: 27,
        transmitHeightM: 1.5,
        receiveHeightM: 1.5,
        distanceKm: 2,
        transmitGainDbi: 0,
        receiveGainDbi: 0,
        sensitivityDbm: -110,
      },
    },
    {
      id: 'vhf',
      label: 'VHF mobile / base · 150 MHz',
      note: 'Example 25 W mobile-to-base link. Heights are above local ground.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 150,
        transmitDbm: 44,
        transmitHeightM: 15,
        receiveHeightM: 2,
        sensitivityDbm: -115,
      },
    },
    {
      id: 'marine',
      label: 'Marine VHF · 156 MHz',
      note: 'Example 25 W ship radios with antennas 10 m and 5 m above sea level.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 156,
        transmitDbm: 44,
        transmitHeightM: 10,
        receiveHeightM: 5,
        sensitivityDbm: -115,
      },
    },
    {
      id: 'airband',
      label: 'Airband VHF · 125 MHz',
      note: 'Example 10 W ground-to-air link, aircraft 1,000 m above the reference surface.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 125,
        transmitDbm: 40,
        transmitHeightM: 10,
        receiveHeightM: 1000,
        distanceKm: 50,
        sensitivityDbm: -107,
      },
    },
    {
      id: 'uhf',
      label: 'UHF repeater · 450 MHz',
      note: 'Example 25 W base station with a 30 m antenna and a handheld receiver.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 450,
        transmitDbm: 44,
        transmitHeightM: 30,
        receiveHeightM: 1.5,
        transmitGainDbi: 5,
        receiveGainDbi: 0,
        sensitivityDbm: -115,
      },
    },
    {
      id: 'telemetry',
      label: 'Telemetry / LoRa · 868 MHz',
      note: 'Example low-power telemetry. Actual sensitivity depends strongly on bandwidth and data rate.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 868,
        transmitDbm: 14,
        transmitHeightM: 5,
        receiveHeightM: 2,
        sensitivityDbm: -130,
        distanceKm: 5,
      },
    },
    {
      id: 'wifi24',
      label: 'Wi-Fi · 2.4 GHz',
      note: 'Example 100 m outdoor link. Receiver sensitivity is data-rate dependent.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 2400,
        transmitDbm: 20,
        transmitHeightM: 3,
        receiveHeightM: 2,
        sensitivityDbm: -85,
        distanceKm: 0.1,
      },
    },
    {
      id: 'wifi5',
      label: 'Directional Wi-Fi · 5.8 GHz',
      note: 'Example aligned directional antennas. A circle is only a distance reference, not the antenna beam.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 5800,
        transmitDbm: 20,
        transmitHeightM: 10,
        receiveHeightM: 10,
        transmitGainDbi: 18,
        receiveGainDbi: 18,
        sensitivityDbm: -85,
        distanceKm: 2,
      },
    },
    {
      id: 'microwave',
      label: 'Microwave point-to-point · 6 GHz',
      note: 'Example directional link. Terrain, rain fading and antenna patterns are not modelled.',
      values: {
        ...DEFAULT_RF_INPUTS,
        frequencyMHz: 6000,
        transmitDbm: 20,
        transmitHeightM: 30,
        receiveHeightM: 30,
        transmitGainDbi: 24,
        receiveGainDbi: 24,
        sensitivityDbm: -80,
        distanceKm: 10,
      },
    },
  ];
