"""Generated public camera catalogue from OSIRIS fac8d1b.

MIT License

Copyright (c) 2026 simplifaisoul

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

# ruff: noqa: E501
DATA = r"""[
{"id": "es-barcelona-2", "lat": 41.38, "lng": 2.18, "name": "Barcelona - Beach Area", "city": "Barcelona", "country": "Spain", "stream_url": "https://www.youtube.com/embed/4DjwrvoTKwk?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0", "stream_type": "iframe", "source": "YouTube Live"},
{"id": "es-madrid-1", "lat": 40.4168, "lng": -3.7038, "name": "Madrid - Puerta del Sol", "city": "Madrid", "country": "Spain", "stream_url": "https://www.youtube.com/embed/4CaHlfpGlAI?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0", "stream_type": "iframe", "source": "YouTube Live"},
{"id": "es-madrid-2", "lat": 40.42, "lng": -3.7, "name": "Madrid - Gran Via", "city": "Madrid", "country": "Spain", "stream_url": "https://www.youtube.com/embed/LSPN10FbR3U?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0", "stream_type": "iframe", "source": "YouTube Live"},
{"id": "sky-es-los-cristianos", "lat": 28.0517, "lng": -16.7155, "name": "Playa de Los Cristianos", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-los-cristianos.html", "source": "SkylineWebcams"},
{"id": "sky-es-las-vistas", "lat": 28.054, "lng": -16.723, "name": "Playa Las Vistas", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-las-vistas.html", "source": "SkylineWebcams"},
{"id": "sky-es-medano-surf", "lat": 28.0445, "lng": -16.537, "name": "El Médano Surf & Kitesurf", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/surf-kitesurf-medano.html", "source": "SkylineWebcams"},
{"id": "sky-es-duque", "lat": 28.08, "lng": -16.74, "name": "Playa del Duque - El Beril", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-del-duque-el-beril.html", "source": "SkylineWebcams"},
{"id": "sky-es-fanabe", "lat": 28.073, "lng": -16.737, "name": "Playa de Fañabé", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-de-fanabe.html", "source": "SkylineWebcams"},
{"id": "sky-es-troya", "lat": 28.06, "lng": -16.73, "name": "Playa de Troya - Las Américas", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-troya.html", "source": "SkylineWebcams"},
{"id": "sky-es-puerto-cruz", "lat": 28.4147, "lng": -16.5476, "name": "Puerto de la Cruz", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/puerto-de-la-cruz-tenerife.html", "source": "SkylineWebcams"},
{"id": "sky-es-la-pinta", "lat": 28.075, "lng": -16.735, "name": "Costa Adeje - Playa La Pinta", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-la-pinta.html", "source": "SkylineWebcams"},
{"id": "sky-es-bahia-cristianos", "lat": 28.049, "lng": -16.718, "name": "Bahía de Los Cristianos", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/bahia-los-cristianos.html", "source": "SkylineWebcams"},
{"id": "sky-es-isora", "lat": 28.194, "lng": -16.856, "name": "Guía de Isora - Playa San Juan", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/guia-de-isora.html", "source": "SkylineWebcams"},
{"id": "sky-es-costa-adeje", "lat": 28.09, "lng": -16.75, "name": "Costa Adeje - Playa Paraíso", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/costa-adeje.html", "source": "SkylineWebcams"},
{"id": "sky-es-punta-brava", "lat": 28.41, "lng": -16.56, "name": "Puerto de la Cruz - Punta Brava", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/punta-brava.html", "source": "SkylineWebcams"},
{"id": "sky-es-masca", "lat": 28.296, "lng": -16.841, "name": "Parque Rural de Teno - Masca", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/masca-valley-tenerife.html", "source": "SkylineWebcams"},
{"id": "sky-es-americas", "lat": 28.056, "lng": -16.728, "name": "Arona - Playa de Las Américas", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-de-las-americas.html", "source": "SkylineWebcams"},
{"id": "sky-es-hidalgo", "lat": 28.56, "lng": -16.33, "name": "Punta del Hidalgo", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/punta-del-hidalgo.html", "source": "SkylineWebcams"},
{"id": "sky-es-lago-martianez", "lat": 28.415, "lng": -16.546, "name": "Puerto de la Cruz - Lago Martiánez", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/puerto-de-la-cruz-lago-martianez.html", "source": "SkylineWebcams"},
{"id": "sky-es-san-telmo", "lat": 28.413, "lng": -16.55, "name": "Puerto de la Cruz - Playa San Telmo", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/puerto-de-la-cruz-playa-san-telmo.html", "source": "SkylineWebcams"},
{"id": "sky-es-medano-playa", "lat": 28.045, "lng": -16.538, "name": "Playa de El Médano", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-de-el-medano.html", "source": "SkylineWebcams"},
{"id": "sky-es-duque2", "lat": 28.081, "lng": -16.741, "name": "Playa del Duque", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/playa-del-duque.html", "source": "SkylineWebcams"},
{"id": "sky-es-catamaran", "lat": 28.07, "lng": -16.735, "name": "Catamarán Royal Delfin", "city": "Tenerife", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/santa-cruz-de-tenerife/catamarano-royal-delfin.html", "source": "SkylineWebcams"},
{"id": "sky-es-canteras-g", "lat": 28.142, "lng": -15.433, "name": "Playa Grande de Las Canteras", "city": "Gran Canaria", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas-gran-canaria/playa-grande-las-canteras.html", "source": "SkylineWebcams"},
{"id": "sky-es-canteras", "lat": 28.14, "lng": -15.438, "name": "Las Palmas - Playa de Las Canteras", "city": "Gran Canaria", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas-gran-canaria/playa-las-canteras.html", "source": "SkylineWebcams"},
{"id": "sky-es-patalavaca", "lat": 27.773, "lng": -15.683, "name": "Patalavaca - Anfi del Mar", "city": "Gran Canaria", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas-gran-canaria/patalavaca.html", "source": "SkylineWebcams"},
{"id": "sky-es-puerto-rico", "lat": 27.787, "lng": -15.71, "name": "Mogán - Playa de Puerto Rico", "city": "Gran Canaria", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas-gran-canaria/mogan-playa-de-puerto-rico.html", "source": "SkylineWebcams"},
{"id": "sky-es-amadores", "lat": 27.792, "lng": -15.72, "name": "Playa de Amadores", "city": "Gran Canaria", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas-gran-canaria/puerto-rico-de-gran-canaria-playa-amadores.html", "source": "SkylineWebcams"},
{"id": "sky-es-playa-cura", "lat": 27.785, "lng": -15.705, "name": "Mogán - Playa del Cura", "city": "Gran Canaria", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas-gran-canaria/mogan-playa-del-cura.html", "source": "SkylineWebcams"},
{"id": "sky-es-pocillos", "lat": 28.921, "lng": -13.651, "name": "Puerto del Carmen - Playa Los Pocillos", "city": "Lanzarote", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas-gran-canaria/puerto-del-carmen-playa-los-pocillos.html", "source": "SkylineWebcams"},
{"id": "sky-es-corralejo", "lat": 28.73, "lng": -13.867, "name": "Fuerteventura - Corralejo", "city": "Fuerteventura", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/corralejo/fuerteventura-corralejo.html", "source": "SkylineWebcams"},
{"id": "sky-es-corralejo-gp", "lat": 28.735, "lng": -13.86, "name": "Grandes Playas de Corralejo", "city": "Fuerteventura", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/corralejo/grandes-playas-corralejo.html", "source": "SkylineWebcams"},
{"id": "sky-es-playa-blanca", "lat": 28.86, "lng": -13.83, "name": "Yaiza - Playa Blanca", "city": "Lanzarote", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/canarias/las-palmas/yaiza-playa-blanca.html", "source": "SkylineWebcams"},
{"id": "sky-es-sol-tiopepe", "lat": 40.417, "lng": -3.7035, "name": "Puerta del Sol - Tío Pepe", "city": "Madrid", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/puerta-del-sol-tio-pepe.html", "source": "SkylineWebcams"},
{"id": "sky-es-sol-mayor", "lat": 40.4172, "lng": -3.705, "name": "Puerta del Sol - Calle Mayor", "city": "Madrid", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/puerta-del-sol-calle-mayor.html", "source": "SkylineWebcams"},
{"id": "sky-es-callao", "lat": 40.42, "lng": -3.707, "name": "Madrid - Plaza del Callao", "city": "Madrid", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/madrid-plaza-del-callao.html", "source": "SkylineWebcams"},
{"id": "sky-es-alcala", "lat": 40.419, "lng": -3.694, "name": "Calle de Alcalá - Cibeles", "city": "Madrid", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/calle-alcala.html", "source": "SkylineWebcams"},
{"id": "sky-es-alhambra", "lat": 37.176, "lng": -3.588, "name": "La Alhambra de Granada", "city": "Granada", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/andalucia/granada/alhambra-de-granada.html", "source": "SkylineWebcams"},
{"id": "sky-es-sevilla-sf", "lat": 37.3891, "lng": -5.9945, "name": "Sevilla - Plaza de San Francisco", "city": "Sevilla", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/andalucia/sevilla/siviglia-plaza-san-francisco.html", "source": "SkylineWebcams"},
{"id": "sky-es-barrosa", "lat": 36.37, "lng": -6.17, "name": "Playa de la Barrosa - Chiclana", "city": "Chiclana", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/andalucia/cadiz/chiclana-de-la-frontera-playa-de-la-barrosa.html", "source": "SkylineWebcams"},
{"id": "sky-es-cocedores", "lat": 37.385, "lng": -1.64, "name": "Pulpí - Playa de los Cocedores", "city": "Pulpí", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/andalucia/almeria/pulpi-playa-de-los-cocedores.html", "source": "SkylineWebcams"},
{"id": "sky-es-benidorm-p", "lat": 38.5322, "lng": -0.127, "name": "Benidorm - Playa de Poniente", "city": "Benidorm", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-valenciana/alicante/benidorm-playa-poniente-sur.html", "source": "SkylineWebcams"},
{"id": "sky-es-benidorm-pp", "lat": 38.534, "lng": -0.125, "name": "Benidorm - Playa de Poniente - Puerto", "city": "Benidorm", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-valenciana/alicante/benidorm-playa-poniente.html", "source": "SkylineWebcams"},
{"id": "sky-es-benidorm-l", "lat": 38.537, "lng": -0.118, "name": "Benidorm - Playa de Levante", "city": "Benidorm", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-valenciana/alicante/benidorm-playa-levante.html", "source": "SkylineWebcams"},
{"id": "sky-es-benidorm-la", "lat": 38.536, "lng": -0.12, "name": "Benidorm - Playa de Levante - Alicante", "city": "Benidorm", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-valenciana/alicante/benidorm-playa-alicante.html", "source": "SkylineWebcams"},
{"id": "sky-es-calpe", "lat": 38.644, "lng": 0.065, "name": "Calpe - Peñón de Ifach", "city": "Calpe", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/comunidad-valenciana/alicante/calpe-penon-de-ifach.html", "source": "SkylineWebcams"},
{"id": "sky-es-lloret", "lat": 41.701, "lng": 2.846, "name": "Lloret de Mar - Costa Brava", "city": "Lloret de Mar", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/cataluna/gerona/lloret-de-mar-costa-brava.html", "source": "SkylineWebcams"},
{"id": "sky-es-calafell", "lat": 41.197, "lng": 1.566, "name": "Calafell - Tarragona", "city": "Calafell", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/cataluna/tarragona/calafell.html", "source": "SkylineWebcams"},
{"id": "sky-es-barcelona-cat", "lat": 41.381, "lng": 2.197, "name": "Tour en Catamarán - Port Olímpic", "city": "Barcelona", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/cataluna/barcelona/catamaran.html", "source": "SkylineWebcams"},
{"id": "sky-es-sardinero", "lat": 43.475, "lng": -3.787, "name": "Santander - Playa del Sardinero", "city": "Santander", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/cantabria/santander/playa-del-sardinero.html", "source": "SkylineWebcams"},
{"id": "sky-es-suances", "lat": 43.432, "lng": -4.042, "name": "Suances - Playa de la Concha", "city": "Suances", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/cantabria/suances/playa-de-la-concha.html", "source": "SkylineWebcams"},
{"id": "sky-es-pujols", "lat": 38.723, "lng": 1.462, "name": "Formentera - Playa de Es Pujols", "city": "Formentera", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/islas-baleares/formentera/playa-es-pujols.html", "source": "SkylineWebcams"},
{"id": "sky-es-bullas", "lat": 38.0497, "lng": -1.67, "name": "Bullas - Plaza de España", "city": "Bullas", "country": "Spain", "external_url": "https://www.skylinewebcams.com/en/webcam/espana/region-de-murcia/murcia/bullas-plaza-de-espana.html", "source": "SkylineWebcams"}
]"""
