# ruff: noqa: RUF001
"""Independent Unicode ICU mapping fixtures, never expected values generated by our converter."""

from datetime import UTC, date, datetime

import pytest

from ase.domain.source_dates import resolve_source_date, solar_hijri_day


# Published Gregorian/Persian mappings, Unicode ICU release-76-1 PersianTest.TestMapping:
# https://github.com/unicode-org/icu/blob/release-76-1/icu4j/main/core/src/test/java/com/ibm/icu/dev/test/calendar/PersianTest.java
@pytest.mark.parametrize(
    ("source", "expected"),
    [
        ((1304, 1, 11), "1925-03-31"),
        ((1312, 12, 23), "1934-03-14"),
        ((1364, 12, 6), "1986-02-25"),
        ((1374, 12, 29), "1996-03-19"),
        ((1375, 1, 1), "1996-03-20"),
        ((1375, 12, 30), "1997-03-20"),
        ((1376, 1, 1), "1997-03-21"),
        ((1384, 6, 31), "2005-09-22"),
        ((1384, 7, 1), "2005-09-23"),
        ((1389, 10, 21), "2011-01-11"),
        ((1404, 1, 1), "2025-03-21"),
        ((1468, 12, 29), "2090-03-19"),
    ],
)
def test_icu_published_calendar_mappings(source, expected):
    assert solar_hijri_day(*source) == date.fromisoformat(expected)


@pytest.mark.parametrize(
    ("raw", "calendar", "status"),
    [
        ("1404-01-01", "unknown", "unsupported"),
        ("1469-01-01", "solar_hijri_icu33", "unsupported"),
        ("1303-01-01", "solar_hijri_icu33", "unsupported"),
        ("1374-12-30", "solar_hijri_icu33", "invalid"),
        ("1404-13-01", "solar_hijri_icu33", "invalid"),
        ("1404/01/01", "solar_hijri_icu33", "unsupported"),
        ("2025-02-29", "gregorian", "invalid"),
        ("2025-03-21T12:30:00", "gregorian", "ambiguous"),
        ("03/04/2025", "gregorian", "invalid"),
        ("garbled", "gregorian", "invalid"),
    ],
)
def test_no_inferred_calendar_zone_or_rollover(raw, calendar, status):
    value = resolve_source_date(raw, "summary", calendar)
    assert value.raw_text == raw and value.status == status
    assert value.value is None and value.day_start is None and value.day_end is None


def test_persian_digits_preserved_and_day_is_not_an_instant():
    raw = "۱۴۰۴-۰۱-۰۱"
    value = resolve_source_date(raw, "summary", "solar_hijri_icu33")
    assert value.raw_text == raw
    assert value.day_start == date(2025, 3, 21) and value.day_end == date(2025, 3, 22)
    assert value.value is None and value.precision == "day"
    assert "timezone" in value.limitations[0]
    assert resolve_source_date(
        "2025-03-21T12:30:00+03:30", "summary", "gregorian"
    ).value == datetime(2025, 3, 21, 9, tzinfo=UTC)
