"""Trusted fixed-file launcher enters its own cgroup before starting the browser."""

import json
import os
from pathlib import Path

from ase.adapters.reports.render_cgroup import RenderCgroup


def main() -> None:
    data = Path("request.json").read_bytes()
    if len(data) > 16_384:
        raise ValueError("Invalid worker request")
    request = json.loads(data)
    if set(request) != {"command", "cgroup", "cgroup_root"}:
        raise ValueError("Invalid worker request")
    command = request["command"]
    if not isinstance(command, list) or not command or any(not isinstance(v, str) for v in command):
        raise ValueError("Invalid worker command")
    job = RenderCgroup(Path(request["cgroup_root"]), Path(request["cgroup"]))
    job.control("cgroup.procs").write_text(str(os.getpid()))
    # Fixed private IPC is generated by the adapter, never accepted from a client.
    os.execve(command[0], command, {"LANG": "C.UTF-8"})  # noqa: S606


if __name__ == "__main__":
    main()
