"""Declared provider geography, separate from adapter delivery and cache state.

These describe the registered catalogues, not complete regional coverage or current
camera availability. Keep the registry coverage test current when adding a provider.
"""

CAMERA_COVERAGE: dict[str, str] = {
    "tfl": "London",
    "hongkong": "Hong Kong",
    "fintraffic": "Finland",
    "wsdot": "Washington State, United States",
    "caltrans": "California, United States",
    "ottawa": "Ottawa, Ontario, Canada",
    "quebec": "Quebec, Canada",
    "ontario": "Ontario, Canada",
    "alberta": "Alberta, Canada",
    "montreal": "Montreal, Quebec, Canada",
    "toronto": "Toronto, Ontario, Canada",
    "drivebc": "British Columbia, Canada",
    "illinois": "Travel Midwest road network, United States",
    "oregon": "Oregon, United States",
    "michigan": "Michigan, United States",
    "indiana": "Indiana, United States",
    "utah": "Utah, United States",
    "nevada": "Nevada, United States",
    "louisiana": "Louisiana, United States",
    "florida": "Florida, United States",
    "georgia": "Georgia, United States",
    "northcarolina": "North Carolina, United States",
    "arizona": "Arizona, United States",
    "newyork": "New York, United States",
    "pennsylvania": "Pennsylvania, United States",
    "newengland": "Vermont, New Hampshire and Maine, United States",
    "idaho": "Idaho, United States",
    "connecticut": "Connecticut, United States",
    "alaska": "Alaska, United States",
    "novascotia": "Nova Scotia, Canada",
    "newbrunswick": "New Brunswick, Canada",
    "saskatchewan": "Saskatchewan, Canada",
    "newfoundland": "Newfoundland and Labrador, Canada",
    "yukon": "Yukon, Canada",
    "manitoba": "Manitoba, Canada",
    "minnesota": "Minnesota, United States",
    "iowa": "Iowa, United States",
    "kansas": "Kansas, United States",
    "massachusetts": "Massachusetts, United States",
    "us-published": "Selected public locations in the United States",
    "asfinag": "ASFINAG motorway network, Austria",
    "netherlands": "Netherlands",
    "iceland": "Iceland",
    "spain-dgt": "DGT road network, Spain",
    "bulgaria": "Bulgaria",
    "serbia": "Serbia",
    "macedonia": "North Macedonia",
    "romania": "Romania",
    "italy": "Italy",
    "czechia": "Czechia",
    "slovakia": "Slovakia",
    "germany": "Germany",
    "france": "France",
    "spain": "Spain",
    "poland": "Poland",
    "switzerland": "Switzerland",
    "greece": "Greece",
    "turkey": "Turkey",
    "australia": "New South Wales, Australia",
    "newzealand": "New Zealand",
    "taiwan": "Taiwan",
    "singapore": "Singapore",
    "asia-live": "Selected public locations in Asia",
    "middle-east": "Selected public locations in the Middle East",
    "thailand": "Thailand",
    "europe-live": "Selected public locations in Europe",
    "taiwan-live": "Taiwan",
    "japan": "Japan",
    "latam-live": "Selected public locations in Latin America",
    "africa-live": "Selected public locations in Africa",
    "eastasia": "East Asia, within the configured directory bounds",
    "seasia": "Southeast Asia, within the configured directory bounds",
    "westasia": "West and Central Asia, within the configured directory bounds",
    "traffic-scotland": "Scotland",
    "durham": "County Durham, England",
    "uk-live": "Selected public locations in the United Kingdom",
    "uk-local": "Selected council, island and crossing locations in Britain and the Isle of Man",
    "northeast": "Tyne and Wear and Northumberland, England",
    "northyorkshire": "North Yorkshire, England",
    "westmorland": "Westmorland and Furness, England",
    "derbyshire": "Derbyshire, England",
    "estonia": "Estonia",
    "tallinn": "Tallinn, Estonia",
    "baltic-live": "Estonia and Latvia",
    "russia-live": "Russia",
    "israel-live": "Jerusalem",
    "iraq-iran-live": "Iraq and Iran",
    "china-live": "China",
    "lithuania": "Lithuania",
    "ireland": "Ireland",
    "norway": "Norway",
    "hungary": "Hungary",
    "autostrade": "Autostrade per l'Italia motorway network, Italy",
    "luxembourg": "Luxembourg",
    "madrid": "Madrid, Spain",
    "lyon": "Lyon, France",
    "queensland": "Queensland, Australia",
    "puertorico": "Puerto Rico",
}
