"""Reviewed country-name subjects, not incident locations or inferred nationalities.

No bare abbreviations, demonyms, capitals or ambiguous short names. Omitted
names deliberately lose recall rather than treating people/states/common nouns
as countries. Add aliases only with ambiguity and exact-span regression tests.
"""

COUNTRY_SUBJECT_ALIASES: dict[str, tuple[str, ...]] = {
    "AD": ("Andorra",),
    "AE": ("United Arab Emirates",),
    "AF": ("Afghanistan",),
    "AG": ("Antigua and Barbuda",),
    "AL": ("Albania",),
    "AM": ("Armenia",),
    "AO": ("Angola",),
    "AR": ("Argentina",),
    "AT": ("Austria",),
    "AU": ("Australia",),
    "AZ": ("Azerbaijan",),
    "BA": ("Bosnia and Herzegovina",),
    "BB": ("Barbados",),
    "BD": ("Bangladesh",),
    "BE": ("Belgium",),
    "BF": ("Burkina Faso",),
    "BG": ("Bulgaria",),
    "BH": ("Bahrain",),
    "BI": ("Burundi",),
    "BJ": ("Benin",),
    "BN": ("Brunei",),
    "BO": ("Bolivia",),
    "BR": ("Brazil",),
    "BS": ("Bahamas",),
    "BT": ("Bhutan",),
    "BW": ("Botswana",),
    "BY": ("Belarus", "白俄罗斯"),
    "BZ": ("Belize",),
    "CA": ("Canada",),
    "CD": ("Democratic Republic of the Congo", "Democratic Republic of Congo"),
    "CF": ("Central African Republic",),
    "CG": ("Republic of the Congo", "Republic of Congo"),
    "CH": ("Switzerland",),
    "CI": ("Côte d’Ivoire", "Côte d'Ivoire", "Ivory Coast"),  # noqa: RUF001 - source spelling
    "CL": ("Chile",),
    "CM": ("Cameroon",),
    "CN": (
        "China",
        "People's Republic of China",
        "中国",
        "中國",
        "中华人民共和国",
        "中華人民共和國",
    ),
    "CO": ("Colombia",),
    "CR": ("Costa Rica",),
    "CU": ("Cuba",),
    "CV": ("Cabo Verde", "Cape Verde"),
    "CY": ("Cyprus",),
    "CZ": ("Czechia", "Czech Republic"),
    "DE": ("Germany", "Deutschland"),
    "DJ": ("Djibouti",),
    "DK": ("Denmark",),
    "DM": ("Dominica",),
    "DO": ("Dominican Republic",),
    "DZ": ("Algeria",),
    "EC": ("Ecuador",),
    "EE": ("Estonia",),
    "EG": ("Egypt",),
    "ER": ("Eritrea",),
    "ES": ("Spain", "España"),
    "ET": ("Ethiopia",),
    "FI": ("Finland",),
    "FJ": ("Fiji",),
    "FR": ("France",),
    "GA": ("Gabon",),
    "GB": ("United Kingdom", "Great Britain"),
    "GD": ("Grenada",),
    "GE": ("Republic of Georgia", "Georgia (country)"),
    "GH": ("Ghana",),
    "GM": ("Gambia",),
    "GN": ("Republic of Guinea",),
    "GQ": ("Equatorial Guinea",),
    "GR": ("Greece",),
    "GT": ("Guatemala",),
    "GW": ("Guinea-Bissau",),
    "GY": ("Guyana",),
    "HN": ("Honduras",),
    "HR": ("Croatia",),
    "HT": ("Haiti",),
    "HU": ("Hungary",),
    "ID": ("Indonesia",),
    "IE": ("Ireland",),
    "IL": ("Israel",),
    "IN": ("India",),
    "IQ": ("Iraq", "العراق"),
    "IR": ("Iran", "ایران", "إيران"),
    "IS": ("Iceland",),
    "IT": ("Italy",),
    "JM": ("Jamaica",),
    "JO": ("Hashemite Kingdom of Jordan",),
    "JP": ("Japan", "日本"),
    "KE": ("Kenya",),
    "KG": ("Kyrgyzstan",),
    "KH": ("Cambodia",),
    "KI": ("Kiribati",),
    "KM": ("Comoros",),
    "KN": ("Saint Kitts and Nevis",),
    "KP": ("North Korea", "Democratic People's Republic of Korea"),
    "KR": ("South Korea", "Republic of Korea"),
    "KW": ("Kuwait",),
    "KZ": ("Kazakhstan",),
    "LA": ("Laos",),
    "LB": ("Lebanon",),
    "LC": ("Saint Lucia",),
    "LI": ("Liechtenstein",),
    "LK": ("Sri Lanka",),
    "LR": ("Liberia",),
    "LS": ("Lesotho",),
    "LT": ("Lithuania",),
    "LU": ("Luxembourg",),
    "LV": ("Latvia",),
    "LY": ("Libya",),
    "MA": ("Morocco",),
    "MC": ("Monaco",),
    "MD": ("Moldova",),
    "ME": ("Montenegro",),
    "MG": ("Madagascar",),
    "MH": ("Marshall Islands",),
    "MK": ("North Macedonia",),
    "ML": ("Mali",),
    "MM": ("Myanmar", "Burma"),
    "MN": ("Mongolia",),
    "MR": ("Mauritania",),
    "MT": ("Malta",),
    "MU": ("Mauritius",),
    "MV": ("Maldives",),
    "MW": ("Malawi",),
    "MX": ("Mexico", "México"),
    "MY": ("Malaysia",),
    "MZ": ("Mozambique",),
    "NA": ("Namibia",),
    "NE": ("Niger",),
    "NG": ("Nigeria",),
    "NI": ("Nicaragua",),
    "NL": ("Netherlands",),
    "NO": ("Norway",),
    "NP": ("Nepal",),
    "NR": ("Nauru",),
    "NZ": ("New Zealand",),
    "OM": ("Oman",),
    "PA": ("Panama",),
    "PE": ("Peru",),
    "PG": ("Papua New Guinea",),
    "PH": ("Philippines",),
    "PK": ("Pakistan",),
    "PL": ("Poland", "Polska"),
    "PS": ("Palestine",),
    "PT": ("Portugal",),
    "PW": ("Palau",),
    "PY": ("Paraguay",),
    "QA": ("Qatar",),
    "RO": ("Romania",),
    "RS": ("Serbia",),
    "RU": ("Russia", "Russian Federation", "Россия", "России", "Россию", "Россией", "俄罗斯"),
    "RW": ("Rwanda",),
    "SA": ("Saudi Arabia",),
    "SB": ("Solomon Islands",),
    "SC": ("Seychelles",),
    "SD": ("Sudan",),
    "SE": ("Sweden",),
    "SG": ("Singapore",),
    "SI": ("Slovenia",),
    "SK": ("Slovakia",),
    "SL": ("Sierra Leone",),
    "SM": ("San Marino",),
    "SN": ("Senegal",),
    "SO": ("Somalia",),
    "SR": ("Suriname",),
    "SS": ("South Sudan",),
    "ST": ("São Tomé and Príncipe", "Sao Tome and Principe"),
    "SV": ("El Salvador",),
    "SY": ("Syria",),
    "SZ": ("Eswatini", "Swaziland"),
    "TD": ("Republic of Chad",),
    "TG": ("Togo",),
    "TH": ("Thailand",),
    "TJ": ("Tajikistan",),
    "TL": ("Timor-Leste", "East Timor"),
    "TM": ("Turkmenistan",),
    "TN": ("Tunisia",),
    "TO": ("Tonga",),
    "TR": ("Türkiye", "Republic of Turkey"),
    "TT": ("Trinidad and Tobago",),
    "TV": ("Tuvalu",),
    "TW": ("Taiwan", "台湾", "臺灣"),
    "TZ": ("Tanzania",),
    "UA": (
        "Ukraine",
        "Украина",
        "Украины",
        "Украине",
        "Украину",
        "Украиной",
        "Україна",
        "України",
        "Україні",
        "Україну",
        "Україною",
        "乌克兰",
    ),
    "UG": ("Uganda",),
    "US": ("United States of America", "United States"),
    "UY": ("Uruguay",),
    "UZ": ("Uzbekistan",),
    "VA": ("Vatican City",),
    "VC": ("Saint Vincent and the Grenadines",),
    "VE": ("Venezuela",),
    "VN": ("Vietnam", "Viet Nam"),
    "VU": ("Vanuatu",),
    "WS": ("Samoa",),
    "XK": ("Kosovo",),
    "YE": ("Yemen",),
    "ZA": ("South Africa",),
    "ZM": ("Zambia",),
    "ZW": ("Zimbabwe",),
}

# Prevent shorter country names from matching a distinct longer place name,
# including when that other country is not selected for this research request.
COUNTRY_SUBJECT_EXCLUSIONS = {
    "CG": COUNTRY_SUBJECT_ALIASES["CD"],
    "CN": ("Republic of China",),
    "IE": ("Northern Ireland",),
    "KR": COUNTRY_SUBJECT_ALIASES["KP"],
    "RU": ("白俄罗斯",),
    "SD": COUNTRY_SUBJECT_ALIASES["SS"],
    "US": ("United States of Mexico",),
    "WS": ("American Samoa",),
}
