"""The maintained economic subject-matter lexicon used to judge headline substance.

Rows, not code. Each theme is a readable label and the phrases that evidence it, so a
new term is one line in the right group. A trailing `*` means "this stem plus any word
characters"; every other phrase matches on word boundaries only, which keeps `tax` out
of `taxi` and `job cuts` out of `new job starters`.

CORE themes are the subject matter of economics: a headline needs at least one of them
before it can be treated as economic reporting. SUPPORTING themes are the institutions
and actors that make a core story more clearly economic; on their own they prove
nothing, because water companies, technology firms and watchdogs appear in stories that
are not about the economy at all. SOFT_FEATURE phrases mark first-person, explainer and
picture-desk framing, which is a feature, not economic reporting, whoever published it.
"""

from collections.abc import Mapping
from types import MappingProxyType

CORE_THEMES: Mapping[str, tuple[str, ...]] = MappingProxyType(
    {
        "the economy": (
            "economy",
            "economic*",
            "macroeconomic*",
            "cost of living",
            "living standards",
            "purchasing power",
        ),
        "inflation and prices": (
            "inflation*",
            "deflation*",
            "disinflation",
            "consumer price*",
            "producer price*",
            "price index",
            "price cap",
            "price rise*",
            "price cut*",
            "price war",
            "prices",
            "pricing",
            "cpi",
            "cpih",
            "rpi",
            "ppi",
            "fares",
            "tariffs on households",
        ),
        "interest rates and monetary policy": (
            "interest rate*",
            "bank rate",
            "base rate",
            "policy rate",
            "repo rate",
            "rate cut*",
            "rate rise*",
            "rate decision",
            "rate hike*",
            "monetary policy",
            "quantitative easing",
            "quantitative tightening",
            "central bank*",
            "federal funds",
            "fomc",
            "mpc",
            "reserve requirement*",
            "money supply",
            "liquidity",
        ),
        "growth and output": (
            "gdp",
            "gross domestic product",
            "growth forecast*",
            "economic growth",
            "recession*",
            "downturn",
            "slowdown",
            "stagnation",
            "stagflation",
            "industrial production",
            "manufacturing output",
            "factory output",
            "pmi",
            "productivity",
            "output",
        ),
        "jobs and wages": (
            "unemployment",
            "unemployed",
            "jobless*",
            "payroll*",
            "labour market",
            "labor market",
            "job cuts",
            "job losses",
            "jobs report",
            "jobs data",
            "jobs market",
            "hiring",
            "redundan*",
            "layoff*",
            "lay-offs",
            "minimum wage",
            "wage*",
            "pay rise*",
            "pay deal*",
            "pay award*",
            "vacancies",
            "workforce",
        ),
        "trade and tariffs": (
            "tariff*",
            "trade deal*",
            "trade war",
            "trade talks",
            "trade deficit",
            "trade surplus",
            "trade balance",
            "imports",
            "exports",
            "import duty",
            "export control*",
            "customs",
            "supply chain*",
            "shipping cost*",
            "freight rate*",
            "wto",
        ),
        "sanctions and restrictions": (
            "sanction*",
            "asset freeze*",
            "embargo*",
            "price cap on",
            "blacklist*",
            "export ban",
        ),
        "currencies": (
            "exchange rate*",
            "currency",
            "currencies",
            "devalu*",
            "foreign exchange",
            "the dollar",
            "sterling",
            "the euro",
            "the yen",
            "the yuan",
            "renminbi",
            "rouble",
            "ruble",
            "the rupee",
            "capital controls",
            "reserves",
        ),
        "bonds and borrowing costs": (
            "bond*",
            "yield*",
            "gilt*",
            "treasuries",
            "sovereign debt",
            "credit rating",
            "borrowing cost*",
            "debt market*",
            "default*",
        ),
        "budgets and fiscal policy": (
            "budget*",
            "fiscal*",
            "public spending",
            "spending review",
            "spending cut*",
            "deficit*",
            "public borrowing",
            "government borrowing",
            "borrowing forecast*",
            "debt interest",
            "national debt",
            "debt ceiling",
            "bailout*",
            "stimulus",
            "austerity",
            "subsid*",
            "state aid",
        ),
        "taxation": (
            "tax",
            "taxes",
            "taxation",
            "surtax",
            "taxpayer*",
            "levy",
            "levies",
            "vat",
            "duty on",
            "windfall",
            "national insurance",
        ),
        "energy and commodities": (
            "oil price*",
            "gas price*",
            "crude",
            "opec",
            "a barrel",
            "per barrel",
            "energy bill*",
            "energy price*",
            "electricity price*",
            "commodit*",
            "gold price*",
            "copper",
            "lng",
            "wheat price*",
            "grain price*",
        ),
        "markets": (
            "stock market*",
            "share price*",
            "shareholder*",
            "equities",
            "stocks",
            "ftse",
            "s&p 500",
            "nasdaq",
            "dow jones",
            "nikkei 225",
            "hang seng",
            "sell-off",
            "investor*",
            "ipo",
            "flotation",
            "market value",
            "valuation",
            "bull market",
            "bear market",
            "hedge fund*",
            "private equity",
        ),
        "company finances": (
            "earnings",
            "profit*",
            "revenue*",
            "sales figures",
            "retail sales",
            "results beat",
            "guidance cut",
            "insolven*",
            "bankrupt*",
            "into administration",
            "liquidation",
            "takeover*",
            "merger*",
            "acquisition*",
            "buyout*",
            "dividend*",
            "funding round",
            "write-down",
            "restructuring",
        ),
        "housing and credit": (
            "mortgage*",
            "house price*",
            "housing market",
            "rents",
            "rent rise*",
            "lending",
            "borrowers",
            "savings rate*",
            "consumer credit",
            "repossession*",
        ),
    }
)

SUPPORTING_THEMES: Mapping[str, tuple[str, ...]] = MappingProxyType(
    {
        "economic institutions": (
            "treasury",
            "chancellor",
            "finance minister*",
            "finance ministry",
            "imf",
            "international monetary fund",
            "oecd",
            "world bank",
            "european central bank",
            "federal reserve",
            "bank of england",
            "bank of japan",
            "bank of canada",
            "people's bank of china",
            "reserve bank",
            "eurozone",
            "office for national statistics",
            "bureau of labor statistics",
        ),
        "commercial actors": (
            "compan*",
            "firm*",
            "business*",
            "industry",
            "manufacturer*",
            "retailer*",
            "lender*",
            "insurer*",
            "bank",
            "banks",
            "banking",
            "sector",
        ),
        "measurement": (
            "forecast*",
            "statistics",
            "index",
            "data show*",
            "survey",
            "estimate*",
            "quarterly",
            "annual*",
            "monthly",
            "year-on-year",
        ),
    }
)

SOFT_FEATURE_PHRASES: tuple[str, ...] = (
    "here's how",
    "here is how",
    "what it's like",
    "how i ",
    "i tried",
    "my first",
    "in pictures",
    "in photos",
    "quiz",
    "recipe*",
    "gift guide",
    "travel guide",
    "best places",
    "things to do",
    "obituar*",
)
