"""Canonical bounded geography and time constraints shared by research entry points."""

from datetime import UTC, datetime, timedelta

from ase.domain.project_time import MAX_PROJECT_INTERVAL

MAX_RESEARCH_COUNTRIES = 8
MAX_RESEARCH_DAYS = 730
MAX_RESEARCH_HOURS = MAX_RESEARCH_DAYS * 24
# ISO 3166-1 alpha-2, plus the application's existing Kosovo code XK.
COUNTRY_CODES = frozenset(
    [
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW",
    ]
)


def normalise_countries(country_iso: str | None, country_isos: object = ()) -> tuple[str, ...]:
    """Reject malformed saved scope instead of silently broadening it to worldwide."""
    if not isinstance(country_isos, tuple | list):
        raise ValueError("Countries must be a list of ISO country codes")
    if len(country_isos) > MAX_RESEARCH_COUNTRIES:
        raise ValueError("Select at most eight countries")
    values = list(country_isos)
    if country_iso is not None:
        if not isinstance(country_iso, str):
            raise ValueError("Invalid legacy country code")
        if values and {value.upper() for value in values if isinstance(value, str)} != {
            country_iso.upper()
        }:
            raise ValueError("Legacy country and countries must describe the same single country")
        values.append(country_iso)
    if any(not isinstance(value, str) or value.upper() not in COUNTRY_CODES for value in values):
        raise ValueError("Select valid ISO country codes")
    return tuple(dict.fromkeys(value.upper() for value in values))


def validate_research_interval(
    since: datetime, until: datetime, *, recorded: bool = False, now: datetime | None = None
) -> None:
    if any(value.utcoffset() is None for value in (since, until)):
        raise ValueError("Research interval bounds must include a timezone")
    since, until = since.astimezone(UTC), until.astimezone(UTC)
    maximum = MAX_PROJECT_INTERVAL if recorded else timedelta(days=MAX_RESEARCH_DAYS)
    if not timedelta(0) < until - since <= maximum:
        raise ValueError(f"Research interval must be positive and at most {maximum.days} days")
    # Frozen plans remain valid as records. Only live entry points supply a clock.
    if now is not None and until > now.astimezone(UTC) + timedelta(minutes=5):
        raise ValueError("Research interval cannot end in the future")


def validate_research_window(hours: int | None) -> None:
    if hours is not None and (
        isinstance(hours, bool)
        or not isinstance(hours, int)
        or not 1 <= hours <= MAX_RESEARCH_HOURS
    ):
        raise ValueError(f"Research window must be between one hour and {MAX_RESEARCH_DAYS} days")
