"""Short transactional operations for report admission after an alert is committed."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ase.domain.warning import Alert


class AlertReportQueue(Protocol):
    async def due(self, now: datetime, limit: int) -> list[UUID]: ...
    async def pending(self, alert_id: UUID) -> tuple[Alert, datetime] | None: ...
    async def link(self, alert_id: UUID, job_id: UUID) -> bool: ...
    async def defer(self, alert_id: UUID, until: datetime, reason: str) -> None: ...
    async def stop(self, alert_id: UUID, reason: str, *, cancelled: bool = False) -> None: ...
