"""Claim persistence. Callers hold the shared administration guard during writes."""

from typing import Protocol
from uuid import UUID

from ase.domain.access import Visibility
from ase.domain.claim_revisions import ClaimRevision
from ase.domain.claim_roots import ClaimRoot


class ClaimRepository(Protocol):
    async def list_ids(
        self, visibility: Visibility, report_id: UUID, version_id: UUID, limit: int, offset: int
    ) -> tuple[tuple[UUID, ...], int]: ...
    async def get(self, claim_id: UUID) -> ClaimRoot | None: ...
    async def revision(self, claim_id: UUID, revision_id: UUID) -> ClaimRevision | None: ...
    async def scope_usage(self, owner_id: UUID, team_id: UUID | None) -> tuple[int, int]: ...
    def storage_size(self, revision: ClaimRevision) -> int: ...
    async def create(self, revision: ClaimRevision, evidence_sha256: str) -> None: ...
    async def append(self, revision: ClaimRevision, base_revision_id: UUID) -> bool: ...
