"""Ports for the direction objects: areas of interest and collection plans."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ase.domain.access import Visibility
from ase.domain.collection import AreaOfInterest, CollectionPlan, LinkedRecords


class AoiRepository(Protocol):
    async def add(self, aoi: AreaOfInterest) -> None: ...
    async def get(self, aoi_id: UUID) -> AreaOfInterest | None: ...
    async def list_all(self) -> list[AreaOfInterest]: ...
    async def list_visible(self, visibility: Visibility) -> list[AreaOfInterest]: ...
    async def linked_plans(self, aoi_id: UUID, visibility: Visibility) -> LinkedRecords:
        """Every collection plan that uses the area, naming only the visible ones."""
        ...

    async def delete(self, aoi_id: UUID) -> None: ...


class PlanRepository(Protocol):
    async def add(self, plan: CollectionPlan) -> None: ...
    async def get(self, plan_id: UUID) -> CollectionPlan | None: ...
    async def list_all(self) -> list[CollectionPlan]: ...
    async def list_visible(self, visibility: Visibility) -> list[CollectionPlan]: ...
    async def save_if_unchanged(self, plan: CollectionPlan, expected_updated_at: datetime) -> bool:
        """Write the plan only while it still has the expected revision, atomically."""
        ...

    async def linked_alert_rules(self, plan_id: UUID, visibility: Visibility) -> LinkedRecords:
        """Every alert rule linked to the plan, naming only the visible ones."""
        ...

    async def delete(self, plan_id: UUID) -> None: ...
