"""Identity decision persistence. Callers hold the shared administration guard during writes."""

from typing import Protocol
from uuid import UUID

from ase.domain.access import Visibility
from ase.domain.identity_review import IdentityDecisionRevision
from ase.domain.identity_roots import IdentityDecisionRoot


class IdentityDecisionRepository(Protocol):
    async def candidate_id(self, version_id: UUID, label: str) -> UUID | None: ...
    async def list_ids(
        self, visibility: Visibility, report_id: UUID, version_id: UUID, limit: int, offset: int
    ) -> tuple[tuple[UUID, ...], int]: ...
    async def get(self, decision_id: UUID) -> IdentityDecisionRoot | None: ...
    async def revision(
        self, decision_id: UUID, revision_id: UUID
    ) -> IdentityDecisionRevision | None: ...
    async def scope_usage(self, owner_id: UUID, team_id: UUID | None) -> tuple[int, int]: ...
    def storage_size(self, revision: IdentityDecisionRevision) -> int: ...
    async def create(self, revision: IdentityDecisionRevision, evidence_sha256: str) -> None: ...
    async def append(self, revision: IdentityDecisionRevision, base_revision_id: UUID) -> bool: ...
