"""Authorised document storage boundary."""

from typing import Protocol
from uuid import UUID

from ase.domain.access import Visibility
from ase.domain.map_workspace import MapWorkspaceDocument, WorkspaceKind


class MapWorkspaceRepository(Protocol):
    async def get(self, document_id: UUID) -> MapWorkspaceDocument | None: ...
    async def list_visible(
        self, visibility: Visibility, kind: WorkspaceKind, limit: int, offset: int
    ) -> list[MapWorkspaceDocument]: ...
    async def scope_count(self, owner: UUID, team_id: UUID | None) -> int: ...
    async def create(self, document: MapWorkspaceDocument) -> None: ...
    async def update(self, document: MapWorkspaceDocument, expected_revision: int) -> bool: ...
    async def remove(self, document_id: UUID) -> None: ...
