"""Storage contract for revocable, read-only private feed credentials."""

from typing import Protocol
from uuid import UUID

from ase.domain.access import Visibility
from ase.domain.notification_feed import FeedEntry, FeedToken


class PrivateFeedRepository(Protocol):
    async def get(self, user_id: UUID) -> FeedToken | None: ...
    async def find(self, token_hash: str) -> FeedToken | None: ...
    async def save(self, token: FeedToken) -> None: ...
    async def revoke(self, user_id: UUID) -> None: ...
    async def entries(self, visibility: Visibility, *, limit: int) -> list[FeedEntry]: ...
