"""Transactional original-byte storage. Caller holds the shared administration guard."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ase.domain.original_assets import OriginalAsset, OriginalAssetContent


class OriginalAssetRepository(Protocol):
    async def expire(self, now: datetime) -> None: ...
    async def usage(
        self, owner_id: UUID | None = None, team_id: UUID | None = None
    ) -> tuple[int, int]: ...
    async def pending_count(self) -> int: ...
    async def create(self, asset: OriginalAsset) -> None: ...
    async def get(self, asset_id: UUID) -> OriginalAsset | None: ...
    async def list(self, report_id: UUID, version_number: int) -> tuple[OriginalAsset, ...]: ...
    async def begin_upload(self, asset_id: UUID, now: datetime) -> bool: ...
    async def activate(self, asset_id: UUID, content: bytes, now: datetime) -> bool: ...
    async def content(self, asset_id: UUID) -> OriginalAssetContent | None: ...
    async def delete(self, asset_id: UUID, now: datetime) -> None: ...
