"""Atomic single-use recovery code persistence."""

from typing import Protocol
from uuid import UUID


class RecoveryCodeRepository(Protocol):
    async def count(self, user_id: UUID, security_version: int) -> int: ...
    async def replace(self, user_id: UUID, security_version: int, hashes: list[str]) -> None: ...
    async def consume(self, user_id: UUID, security_version: int, code_hash: str) -> bool: ...
    async def clear(self, user_id: UUID) -> None: ...
