"""Relationship decision persistence. Callers hold the shared administration guard during writes."""

from typing import Protocol
from uuid import UUID

from ase.domain.access import Visibility
from ase.domain.relationship_review import RelationshipReviewRevision
from ase.domain.relationship_roots import RelationshipReviewRoot


class RelationshipReviewRepository(Protocol):
    async def assertion_id(self, version_id: UUID, label: str) -> UUID | None: ...
    async def list_ids(
        self, visibility: Visibility, report_id: UUID, version_id: UUID, limit: int, offset: int
    ) -> tuple[tuple[UUID, ...], int]: ...
    async def get(self, relationship_id: UUID) -> RelationshipReviewRoot | None: ...
    async def revision(
        self, relationship_id: UUID, revision_id: UUID
    ) -> RelationshipReviewRevision | None: ...
    async def scope_usage(self, owner_id: UUID, team_id: UUID | None) -> tuple[int, int]: ...
    def storage_size(self, revision: RelationshipReviewRevision) -> int: ...
    async def create(self, revision: RelationshipReviewRevision, evidence_sha256: str) -> None: ...
    async def append(
        self, revision: RelationshipReviewRevision, base_revision_id: UUID
    ) -> bool: ...
