"""Persistence ports."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ase.domain.audit import AuditEntry
from ase.domain.tokens import PasswordToken, RefreshToken
from ase.domain.users import AccountRequest, RequestStatus, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...
    async def list_all(self) -> list[User]: ...


class AccountRequestRepository(Protocol):
    async def get(self, request_id: UUID) -> AccountRequest | None: ...
    async def add(self, request: AccountRequest) -> None: ...
    async def save(self, request: AccountRequest) -> None: ...
    async def list_by_status(self, status: RequestStatus) -> list[AccountRequest]: ...
    async def has_pending_for_email(self, email: str) -> bool: ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> None: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def save(self, token: RefreshToken) -> None: ...
    async def consume(self, token_id: UUID, now: datetime) -> bool:
        """Atomically claim an unexpired token only if neither it nor its family is revoked."""
        ...

    async def revoke_family(self, family_id: UUID, now: datetime) -> int: ...
    async def revoke_all_for_user(self, user_id: UUID, now: datetime) -> int: ...


class PasswordTokenRepository(Protocol):
    async def add(self, token: PasswordToken) -> None: ...
    async def get_by_hash(self, token_hash: str) -> PasswordToken | None: ...
    async def save(self, token: PasswordToken) -> None: ...
    async def consume(self, token_id: UUID, now: datetime) -> bool:
        """Atomically mark an unexpired, unused token as used in the current transaction."""
        ...

    async def revoke_all_for_user(self, user_id: UUID, now: datetime) -> int: ...


class AuditLogRepository(Protocol):
    async def add(self, entry: AuditEntry) -> None: ...
    async def list_before(self, before: int | None, limit: int) -> list[AuditEntry]: ...


class UnitOfWork(Protocol):
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
