"""SEC data and private, session-bound selection boundaries."""

from datetime import date
from typing import Protocol
from uuid import UUID

from ase.application.dto import AccessClaims
from ase.application.ports.research_inputs import InputExtraction
from ase.domain.sec_filings import SecFiling, SecFilingChoice, SecFilingPage


class SecFilingProvider(Protocol):
    async def list(
        self, cik: str, since: date, until: date, page: int, offset: int
    ) -> SecFilingPage: ...
    async def fetch(self, filing: SecFiling) -> tuple[InputExtraction, bytes]: ...


class SecSelectionStore(Protocol):
    def issue(self, claims: AccessClaims, page: SecFilingPage) -> tuple[SecFilingChoice, ...]: ...
    def get(self, claims: AccessClaims, selection_id: UUID) -> SecFilingChoice: ...
    def reserve_original(self, claims: AccessClaims, selection_id: UUID) -> None: ...
    def put_original(self, claims: AccessClaims, selection_id: UUID, data: bytes) -> None: ...
    def release_original(self, selection_id: UUID) -> None: ...
    def original(self, claims: AccessClaims, selection_id: UUID) -> bytes: ...
