"""Persistence boundary for scoped reviewer decisions and frozen reviewed projections."""

from typing import Protocol
from uuid import UUID

from ase.domain.source_review_records import SourceReviewSnapshot
from ase.domain.source_reviews import SourceReviewRevision, SourceReviewScope


class SourceReviewRepository(Protocol):
    async def history(
        self, scope: SourceReviewScope, key: str
    ) -> tuple[SourceReviewRevision, ...]: ...
    async def scope_usage(self, scope: SourceReviewScope) -> tuple[int, int]: ...
    async def append(self, value: SourceReviewRevision) -> bool: ...
    async def snapshot_count(self, report_version_id: UUID) -> int: ...
    async def add_snapshot(self, value: SourceReviewSnapshot) -> None: ...
    async def snapshot(self, snapshot_id: UUID) -> SourceReviewSnapshot | None: ...
