"""Caller-owned transactions for immutable subscription revisions and editions."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ase.domain.subscription_editions import (
    EditionAttempt,
    EditionDelivery,
    SubscriptionEdition,
    SubscriptionLineage,
    SubscriptionRevision,
)


class SubscriptionEditionRepository(Protocol):
    async def add_revision(self, revision: SubscriptionRevision) -> SubscriptionRevision: ...
    async def get_revision(
        self, subscription_id: UUID, revision: int
    ) -> SubscriptionRevision | None: ...
    async def latest_revision(self, subscription_id: UUID) -> SubscriptionRevision | None: ...
    async def reserve(self, edition: SubscriptionEdition) -> SubscriptionEdition: ...
    async def get(self, edition_id: UUID) -> SubscriptionEdition | None: ...
    async def get_by_job(self, job_id: UUID) -> SubscriptionEdition | None: ...
    async def get_by_version(self, version_id: UUID) -> SubscriptionEdition | None: ...
    async def active(self, subscription_id: UUID) -> SubscriptionEdition | None: ...
    async def due(self, now: datetime, limit: int = 50) -> list[SubscriptionEdition]: ...
    async def history(
        self, subscription_id: UUID, *, limit: int = 50, offset: int = 0
    ) -> list[SubscriptionEdition]: ...
    async def advance(
        self, edition: SubscriptionEdition, *, expected_revision: int
    ) -> SubscriptionEdition | None: ...
    async def get_lineage(self, subscription_id: UUID) -> SubscriptionLineage | None: ...
    async def save_lineage(
        self, lineage: SubscriptionLineage, *, expected_revision: int | None
    ) -> SubscriptionLineage | None: ...
    async def add_attempt(self, attempt: EditionAttempt) -> None: ...
    async def attempts(self, edition_id: UUID, limit: int = 50) -> list[EditionAttempt]: ...
    async def add_delivery(self, delivery: EditionDelivery) -> None: ...
    async def deliveries(self, edition_id: UUID, limit: int = 50) -> list[EditionDelivery]: ...
