"""Team persistence, including a transaction-scoped mutation lock."""

from typing import Protocol
from uuid import UUID

from ase.domain.teams import Team, TeamMember, TeamMembership


class TeamRepository(Protocol):
    async def add(self, team: Team) -> None: ...
    async def get(self, team_id: UUID) -> Team | None: ...
    async def get_for_update(self, team_id: UUID) -> Team | None:
        """Serialise team/archive/membership mutations until transaction completion."""
        ...

    async def save(self, team: Team) -> None: ...
    async def list_visible(self, user_id: UUID, *, administrator: bool) -> list[Team]: ...
    async def count_active_created_by(self, user_id: UUID) -> int: ...
    async def get_membership(self, team_id: UUID, user_id: UUID) -> TeamMembership | None: ...
    async def memberships_for_user(self, user_id: UUID) -> list[TeamMembership]: ...
    async def list_members(self, team_id: UUID) -> list[TeamMember]: ...
    async def count_members(self, team_id: UUID) -> int: ...
    async def count_active_managers(self, team_id: UUID) -> int: ...
    async def put_membership(self, membership: TeamMembership) -> None: ...
    async def remove_membership(self, team_id: UUID, user_id: UUID) -> None: ...
