"""TOTP cryptography and atomic persistence boundaries."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ase.domain.totp import TotpEnrolment, TotpState


class TotpProvider(Protocol):
    @property
    def available(self) -> bool: ...
    def enrol(self, email: str) -> TotpEnrolment: ...
    def verify(self, encrypted: str, code: str, now: datetime) -> int | None: ...


class TotpRepository(Protocol):
    async def get(self, user_id: UUID) -> TotpState | None: ...
    async def begin(self, user_id: UUID, encrypted: str, expires: datetime) -> bool: ...
    async def confirm(self, user_id: UUID, encrypted: str, step: int, now: datetime) -> bool: ...
    async def consume(self, user_id: UUID, encrypted: str, step: int) -> bool: ...
    async def clear(self, user_id: UUID) -> None: ...
