"""Ports for indicators, alerts and the routes an alert travels."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from ase.domain.access import Visibility
from ase.domain.warning import Alert, Indicator


class IndicatorRepository(Protocol):
    async def add(self, indicator: Indicator) -> None: ...
    async def get(self, indicator_id: UUID) -> Indicator | None: ...
    async def list_all(self, visibility: Visibility) -> list[Indicator]: ...
    async def save(self, indicator: Indicator) -> None: ...
    async def delete(self, indicator_id: UUID) -> None: ...


class AlertRepository(Protocol):
    async def get(self, alert_id: UUID) -> Alert | None: ...
    async def list_recent(
        self, since: datetime, limit: int, visibility: Visibility
    ) -> list[Alert]: ...
    async def save(self, alert: Alert) -> None: ...


class WarningStore(Protocol):
    """What the background evaluator needs; each call runs in its own session."""

    async def enabled_indicators(self) -> list[Indicator]: ...
    async def can_run(self, indicator: Indicator) -> bool: ...
    async def latest_alert(self, indicator_id: UUID) -> Alert | None: ...
    async def add_alert(self, alert: Alert, indicator: Indicator) -> bool: ...
    async def attach_report(self, alert_id: UUID, report_id: UUID) -> bool: ...
    async def prune(self, before: datetime) -> int: ...


class AlertNotifier(Protocol):
    async def notify(self, alert: Alert, indicator: Indicator) -> bool: ...
