import type { RelationshipRevision, RelationshipRoot } from '@/lib/api/relationships';
export const relationshipRevision: RelationshipRevision = {
  id: 'relationship-revision-1',
  relationship_id: 'relationship-1',
  report_id: 'report-1',
  report_version_id: 'version-1',
  number: 1,
  previous_id: null,
  assertion: {
    evidence_label: 'E1',
    event_id: 'event-1',
    source_id: 'research-gleif-direct-parent',
    source_content_hash: 'hash',
    child_lei: '00123456789012345678',
    parent_lei: '99123456789012345678',
    kind: 'direct',
    relationship_type: 'IS_DIRECTLY_CONSOLIDATED_BY',
    captured_at: '2026-09-07T00:00:00Z',
    published_at: null,
    attributes: [
      { key: 'reported_relationship_status', value: 'ACTIVE' },
      { key: 'reported_periods_omitted', value: 2 },
    ],
    periods: [{ type: 'ACCOUNTING_PERIOD', startDate: '2020-01-01', endDate: '2020-12-31' }],
    periods_state: 'parsed',
  },
  disposition: 'unresolved',
  rationale: 'Period needs further evidence.',
  unresolved_conflicts: ['Current validity is unknown.'],
  citations: [],
  authored_by: 'user-1',
  created_at: '2026-09-07T01:00:00Z',
};
export const relationshipRoot: RelationshipRoot = {
  id: 'relationship-1',
  report_id: 'report-1',
  report_version_id: 'version-1',
  report_version_number: 1,
  created_by: 'user-1',
  team_id: null,
  evidence_label: 'E1',
  evidence_sha256: 'hash',
  latest_revision_id: relationshipRevision.id,
  created_at: relationshipRevision.created_at,
};
