import type { UkraineReference } from '@/lib/api/ukraine';

export const ukraineReference: UkraineReference = {
  retrieved_at: '2026-09-13T23:00:00Z',
  source_note: 'Hand-written reference notes; background, not intelligence.',
  specialities: [
    {
      key: 'drones',
      label: 'Drones',
      subgroups: { reconnaissance: 'Reconnaissance', fpv: 'FPV strike drones' },
    },
    { key: 'tanks', label: 'Tanks', subgroups: { main_battle: 'Main battle tanks' } },
    {
      key: 'sensors',
      label: 'Radars, sensors and imagery',
      subgroups: { counter_battery: 'Counter-battery and ground surveillance radars' },
    },
  ],
  themes: { ground: 'Ground war', air: 'Air and missile war', diplomacy: 'Diplomacy and aid' },
  equipment: [
    {
      id: 'ru-orlan-10',
      side: 'ru',
      group: 'drones',
      subgroup: 'reconnaissance',
      name: 'Orlan-10',
      origin: 'Russia',
      role: 'Tactical reconnaissance drone',
      description: 'A catapult-launched reconnaissance drone used to spot for artillery.',
      numbers: 'Oryx has documented over a thousand losses.',
      wikidata_id: 'Q4336510',
      image_id: 'ru-orlan-10',
      as_of: '2026-06-30',
      links: [{ label: 'Wikipedia article', url: 'https://en.wikipedia.org/wiki/Orlan-10' }],
    },
    {
      id: 'ua-fpv',
      side: 'ua',
      group: 'drones',
      subgroup: 'fpv',
      name: 'FPV strike drones (Ukraine)',
      origin: 'Ukraine',
      role: 'First-person-view quadcopters carrying a warhead',
      description: 'Cheap quadcopters flown through goggles into vehicles and positions.',
      numbers: null,
      wikidata_id: 'Q124249336',
      image_id: null,
      as_of: '2026-06-30',
      links: [{ label: 'Wikipedia article', url: 'https://en.wikipedia.org/wiki/FPV_drone' }],
    },
    {
      id: 'ru-t-90m',
      side: 'ru',
      group: 'tanks',
      subgroup: 'main_battle',
      name: 'T-90M Proryv',
      origin: 'Russia',
      role: 'Modernised main battle tank',
      description: 'The T-90M is the best Russian tank in quantity.',
      numbers: 'Oryx documents over a hundred T-90M losses.',
      wikidata_id: 'Q123490387',
      image_id: 'ru-t-90m',
      as_of: '2026-06-30',
      links: [{ label: 'Wikipedia article', url: 'https://en.wikipedia.org/wiki/T-90M' }],
    },
    {
      id: 'ru-zoopark-1m',
      side: 'ru',
      group: 'sensors',
      subgroup: 'counter_battery',
      name: '1L260 Zoopark-1M',
      origin: 'Russia',
      role: 'Counter-battery radar',
      description: 'Tracks incoming shells back to the gun that fired them.',
      numbers: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2024-01-31',
      links: [{ label: 'Wikipedia article', url: 'https://en.wikipedia.org/wiki/Zoopark-1' }],
    },
    {
      id: 'ua-tpq-36',
      side: 'ua',
      group: 'sensors',
      subgroup: 'counter_battery',
      name: 'AN/TPQ-36 Firefinder',
      origin: 'United States',
      role: 'Counter-battery radar',
      description: 'An American counter-battery radar supplied to Ukraine from 2022.',
      numbers: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2026-06-30',
      links: [{ label: 'Wikipedia article', url: 'https://en.wikipedia.org/wiki/AN/TPQ-36' }],
    },
  ],
  forces: [
    {
      id: 'ru-supreme',
      side: 'ru',
      parent_id: null,
      name: 'Supreme Commander-in-Chief',
      role: 'The President of Russia commands the armed forces.',
      commander: 'Vladimir Putin',
      figure_id: 'ru-head-of-state',
      strength: null,
      wikidata_id: 'Q7747',
      image_id: 'ru-supreme',
      as_of: '2026-06-30',
      links: [{ label: 'Wikipedia article', url: 'https://en.wikipedia.org/wiki/Vladimir_Putin' }],
    },
    {
      id: 'ru-general-staff',
      side: 'ru',
      parent_id: 'ru-supreme',
      name: 'General Staff and Joint Grouping of Forces',
      role: 'Valery Gerasimov has commanded the Joint Grouping since January 2023.',
      commander: 'Valery Gerasimov',
      figure_id: null,
      strength: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2026-06-30',
      links: [],
    },
    {
      id: 'ru-groupings',
      side: 'ru',
      parent_id: 'ru-general-staff',
      name: 'Groupings of forces',
      role: 'The front is divided into named groupings built on district headquarters.',
      commander: null,
      figure_id: null,
      strength: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2026-06-30',
      links: [],
    },
    {
      id: 'ru-north',
      side: 'ru',
      parent_id: 'ru-groupings',
      name: 'Grouping North',
      role: 'Formed in 2024 for the Kharkiv incursion and the defence of Kursk.',
      commander: null,
      figure_id: null,
      strength: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2024-06-30',
      links: [],
    },
    {
      id: 'ru-south',
      side: 'ru',
      parent_id: 'ru-groupings',
      name: 'Grouping South',
      role: 'Responsible for Bakhmut, Chasiv Yar and Toretsk.',
      commander: null,
      figure_id: null,
      strength: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2026-06-30',
      links: [],
    },
    {
      id: 'ua-president',
      side: 'ua',
      parent_id: null,
      name: 'Supreme Commander-in-Chief',
      role: 'The President of Ukraine commands the armed forces.',
      commander: 'Volodymyr Zelenskyy',
      figure_id: 'ua-head-of-state',
      strength: 'Around one million personnel by official statements.',
      wikidata_id: 'Q3874799',
      image_id: null,
      as_of: '2026-06-30',
      links: [],
    },
    {
      id: 'ua-general-staff',
      side: 'ua',
      parent_id: 'ua-president',
      name: 'General Staff',
      role: 'Plans operations and publishes the daily loss claims shown on this page.',
      commander: null,
      figure_id: null,
      strength: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2026-06-30',
      links: [],
    },
    {
      id: 'ua-unmanned',
      side: 'ua',
      parent_id: 'ua-general-staff',
      name: 'Unmanned Systems Forces',
      role: 'A separate branch created in 2024 for drone units.',
      commander: null,
      figure_id: null,
      strength: null,
      wikidata_id: null,
      image_id: null,
      as_of: '2026-06-30',
      links: [],
    },
  ],
  phases: [
    {
      id: 'invasion',
      label: 'Full-scale invasion, February to April 2022',
      start: '2022-02-24',
      end: '2022-04-07',
      summary: 'Russia attacked from the north, east and south; the drive on Kyiv failed.',
    },
    {
      id: '2026',
      label: '2026',
      start: '2026-01-01',
      end: null,
      summary: 'The war continued into its fifth year.',
    },
  ],
  events: [
    {
      id: 'invasion-day',
      phase_id: 'invasion',
      on: '2022-02-24',
      title: 'The full-scale invasion begins',
      text: 'Putin announced a special military operation and missiles struck cities across Ukraine.',
      theme: 'ground',
      wikidata_id: 'Q110999040',
      image_id: 'invasion-day',
      links: [
        {
          label: 'Wikipedia article',
          url: 'https://en.wikipedia.org/wiki/Russian_invasion_of_Ukraine',
        },
      ],
    },
    {
      id: 'peace-plan-2025',
      phase_id: '2026',
      on: '2026-01-15',
      title: 'Talks without a ceasefire',
      text: 'Revised peace drafts were rejected and fighting continued.',
      theme: 'diplomacy',
      wikidata_id: null,
      image_id: null,
      links: [],
    },
  ],
  images: {
    'ru-orlan-10': {
      id: 'ru-orlan-10',
      licence: 'CC BY-SA 4.0',
      credit: 'Someone',
      source_url: 'https://commons.wikimedia.org/wiki/File:Orlan.jpg',
      width: 480,
      height: 320,
    },
    'ru-t-90m': {
      id: 'ru-t-90m',
      licence: 'CC BY 4.0',
      credit: 'Mil.ru',
      source_url: 'https://commons.wikimedia.org/wiki/File:T-90M.jpg',
      width: 480,
      height: 300,
    },
    'ru-supreme': {
      id: 'ru-supreme',
      licence: 'CC BY 4.0',
      credit: 'Presidential Press Service',
      source_url: 'https://commons.wikimedia.org/wiki/File:Putin.jpg',
      width: 480,
      height: 720,
    },
    'invasion-day': {
      id: 'invasion-day',
      licence: 'CC BY-SA 4.0',
      credit: 'Someone else',
      source_url: 'https://commons.wikimedia.org/wiki/File:Invasion.jpg',
      width: 480,
      height: 270,
    },
  },
};
