"""Builds the land mask behind the product page's dotted globe.

Rasterises the packaged Natural Earth 1:110m country polygons (public domain) onto a
one-degree latitude and longitude grid and writes the result as a base64 bitmap that
the frontend decodes once. Rows run from 90 N southwards, columns from 180 W eastwards,
and a set bit means the cell centre lies on land. Re-run after the countries change:

    python scripts/build_product_land_mask.py
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "backend/src/ase/resources/countries_110m.json"
OUTPUT = ROOT / "frontend/src/features/product/scenes/landMask.generated.ts"
COLUMNS = 360
ROWS = 180

Ring = list[list[float]]


def inside(ring: Ring, lon: float, lat: float) -> bool:
    """Even-odd ray casting; the 110m outlines never cross the antimeridian mid-ring."""
    result = False
    previous = ring[-1]
    for point in ring:
        (x1, y1), (x2, y2) = previous, point
        if (y1 > lat) != (y2 > lat) and lon < (x2 - x1) * (lat - y1) / (y2 - y1) + x1:
            result = not result
        previous = point
    return result


def on_land(polygons: list[list[Ring]], lon: float, lat: float) -> bool:
    for polygon in polygons:
        outer, *holes = polygon
        if inside(outer, lon, lat) and not any(inside(hole, lon, lat) for hole in holes):
            return True
    return False


def build() -> tuple[str, int]:
    data = json.loads(SOURCE.read_text("utf-8"))
    polygons = [polygon for country in data["countries"] for polygon in country["polygons"]]
    bits = bytearray((COLUMNS * ROWS + 7) // 8)
    land = 0
    for row in range(ROWS):
        lat = 89.5 - row
        for column in range(COLUMNS):
            lon = -179.5 + column
            if on_land(polygons, lon, lat):
                index = row * COLUMNS + column
                bits[index >> 3] |= 1 << (index & 7)
                land += 1
    return base64.b64encode(bytes(bits)).decode("ascii"), land


def main() -> None:
    encoded, land = build()
    lines = [encoded[i : i + 96] for i in range(0, len(encoded), 96)]
    body = "\n".join(f"  '{line}' +" for line in lines).rstrip(" +")
    OUTPUT.write_text(
        "// Generated by scripts/build_product_land_mask.py from Natural Earth 1:110m\n"
        "// (public domain). Do not edit by hand.\n"
        f"export const LAND_MASK_COLUMNS = {COLUMNS};\n"
        f"export const LAND_MASK_ROWS = {ROWS};\n"
        f"export const LAND_MASK_CELLS = {land};\n"
        f"export const LAND_MASK_BASE64 =\n{body};\n",
        "utf-8",
        newline="\n",
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {land} land cells.")


if __name__ == "__main__":
    main()
