"""Reviewed editorial routing, never incident geography or a language-country inference."""

NATIVE_COUNTRIES: dict[str, tuple[str, ...]] = {
    "bbc_arabic": (
        "AE",
        "BH",
        "DZ",
        "EG",
        "IQ",
        "JO",
        "KW",
        "LB",
        "LY",
        "MA",
        "OM",
        "PS",
        "QA",
        "SA",
        "SD",
        "SY",
        "TN",
        "YE",
    ),
    "bbc_hindi": ("IN",),
    "bbc_urdu": ("PK", "IN", "AF"),
    "bbc_japanese": ("JP",),
    "bbc_korean": ("KR", "KP"),
    "bbc_hausa": ("NG", "NE"),
    "bbc_swahili": ("KE", "TZ", "UG", "RW", "BI", "CD"),
    "bbc_afrique": (
        "BJ",
        "BF",
        "BI",
        "CM",
        "CF",
        "TD",
        "CG",
        "CD",
        "CI",
        "DJ",
        "GA",
        "GN",
        "ML",
        "NE",
        "RW",
        "SN",
        "TG",
    ),
    "trt_haber_tr": ("TR",),
    "ndtv_hindi": ("IN",),
    "express_urdu": ("PK",),
    "radio_okapi_fr": ("CD",),
    "deutschlandfunk_de": ("DE",),
    "anadolu_ar": ("TR", "EG", "IQ", "JO", "LB", "LY", "PS", "SA", "SD", "SY", "YE"),
    "maariv_he": ("IL",),
}
