"""Worldwide publisher feeds, verified 13 September 2026, with declared languages."""

from ase.adapters.feeds.rss_news_seed import PERSONAL_TERMS, news_seed
from ase.adapters.feeds.rss_seeds import RssSeed

WORLD_NEWS_SEEDS: tuple[RssSeed, ...] = (
    news_seed(
        "cbc_canada",
        "CBC News top stories",
        "CBC/Radio-Canada",
        "https://www.cbc.ca/webfeed/rss/rss-topstories",
        "https://www.cbc.ca/news",
        "Canadian and international headlines.",
    ),
    news_seed(
        "npr_world",
        "NPR World",
        "NPR",
        "https://feeds.npr.org/1004/rss.xml",
        "https://www.npr.org/sections/world/",
        "International reporting from a US publisher.",
    ),
    news_seed(
        "pbs_news",
        "PBS News headlines",
        "NewsHour Productions",
        "https://www.pbs.org/newshour/feeds/rss/headlines",
        "https://www.pbs.org/newshour/",
        "US and international news, including broadcast segment headlines.",
    ),
    news_seed(
        "nytimes_world",
        "The New York Times World",
        "The New York Times Company",
        "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        "https://www.nytimes.com/section/world",
        "International news; linked articles may be paywalled.",
    ),
    news_seed(
        "rfi_en",
        "RFI English",
        "France Médias Monde",
        "https://www.rfi.fr/en/rss",
        "https://www.rfi.fr/en/",
        "France, Africa and international news in English.",
    ),
    news_seed(
        "rfi_fr",
        "RFI French",
        "France Médias Monde",
        "https://www.rfi.fr/fr/rss",
        "https://www.rfi.fr/fr/",
        "France, Africa and international news in French.",
        language="fr",
    ),
    news_seed(
        "euronews",
        "Euronews",
        "Euronews",
        "https://www.euronews.com/rss?level=theme&name=news",
        "https://www.euronews.com/",
        "European and international news.",
    ),
    news_seed(
        "el_pais",
        "El País Spanish",
        "PRISA",
        "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "https://elpais.com/",
        "Spain, Latin America and international news in Spanish.",
        language="es",
    ),
    news_seed(
        "publico_pt",
        "Público Portugal",
        "Público",
        "https://feeds.feedburner.com/PublicoRSS",
        "https://www.publico.pt/",
        "Portuguese and international news in Portuguese.",
        language="pt",
    ),
    news_seed(
        "france24_ar",
        "France 24 Arabic",
        "France Médias Monde",
        "https://www.france24.com/ar/rss",
        "https://www.france24.com/ar/",
        "Middle East, North Africa and international news in Arabic.",
        language="ar",
    ),
    news_seed(
        "africanews",
        "Africanews",
        "Euronews",
        "https://www.africanews.com/feed/rss",
        "https://www.africanews.com/",
        "African regional and international news.",
    ),
    news_seed(
        "premium_times",
        "Premium Times Nigeria",
        "Premium Times",
        "https://www.premiumtimesng.com/feed",
        "https://www.premiumtimesng.com/",
        "Nigerian national news and regional reporting.",
    ),
    news_seed(
        "myjoyonline",
        "MyJoyOnline Ghana",
        "Multimedia Group",
        "https://www.myjoyonline.com/feed/",
        "https://www.myjoyonline.com/",
        "Ghanaian national news and regional reporting.",
    ),
    news_seed(
        "agencia_brasil_en",
        "Agência Brasil English",
        "Empresa Brasil de Comunicação",
        "https://agenciabrasil.ebc.com.br/en/rss/ultimasnoticias/feed.xml",
        "https://agenciabrasil.ebc.com.br/en",
        "Brazilian public news agency, English edition.",
        flags=frozenset({"state_owned", "interested_party"}),
    ),
    news_seed(
        "mercopress",
        "MercoPress",
        "MercoPress",
        "https://en.mercopress.com/rss",
        "https://en.mercopress.com/",
        "South Atlantic and South American regional reporting.",
    ),
    news_seed(
        "batimes",
        "Buenos Aires Times",
        "Editorial Perfil",
        "https://www.batimes.com.ar/feed",
        "https://www.batimes.com.ar/",
        "Argentine and Latin American news in English.",
    ),
    news_seed(
        "cna_asia",
        "CNA Asia",
        "Mediacorp",
        "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
        "https://www.channelnewsasia.com/asia",
        "Asian regional news.",
        terms=PERSONAL_TERMS,
    ),
    news_seed(
        "japan_times",
        "The Japan Times",
        "The Japan Times",
        "https://www.japantimes.co.jp/feed/",
        "https://www.japantimes.co.jp/",
        "Japanese and international news in English; linked articles may be paywalled.",
    ),
    news_seed(
        "indian_express",
        "The Indian Express",
        "The Indian Express Group",
        "https://indianexpress.com/feed/",
        "https://indianexpress.com/",
        "Indian national and international headlines; at most 200 feed items.",
    ),
    news_seed(
        "hindustan_times",
        "Hindustan Times India",
        "HT Media",
        "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
        "https://www.hindustantimes.com/india-news",
        "Indian national news.",
    ),
    news_seed(
        "antara_en",
        "ANTARA News English",
        "ANTARA",
        "https://en.antaranews.com/rss/news.xml",
        "https://en.antaranews.com/",
        "Indonesian public news agency, English edition.",
        flags=frozenset({"state_owned", "interested_party"}),
    ),
    news_seed(
        "bangkok_post",
        "Bangkok Post",
        "Bangkok Post",
        "https://www.bangkokpost.com/rss/data/topstories.xml",
        "https://www.bangkokpost.com/",
        "Thai national and regional headlines.",
    ),
    news_seed(
        "abc_australia",
        "ABC News Australia",
        "Australian Broadcasting Corporation",
        "https://www.abc.net.au/news/feed/51120/rss.xml",
        "https://www.abc.net.au/news/",
        "Australian and international news.",
    ),
    news_seed(
        "newsroom_nz",
        "Newsroom New Zealand",
        "Newsroom",
        "https://newsroom.co.nz/feed/",
        "https://newsroom.co.nz/",
        "New Zealand news and analysis.",
    ),
)
