"""News outlets, verified live on 5 September 2026; grades follow docs/02_DATA_SOURCES.md."""

from __future__ import annotations

from ase.adapters.feeds.rss_seeds import (
    PRESS,
    STATE_MEDIA,
    WIRE,
    B,
    C,
    N,
    RssSeed,
    seed,
)

OUTLET_SEEDS: tuple[RssSeed, ...] = (
    seed(
        "bbc_world",
        "BBC News World",
        "BBC",
        N,
        "https://feeds.bbci.co.uk/news/world/rss.xml",
        B,
        15,
        WIRE,
        homepage="https://www.bbc.co.uk/news/world",
    ),
    seed(
        "dw_world",
        "DW World",
        "Deutsche Welle",
        N,
        "https://rss.dw.com/rdf/rss-en-world",
        B,
        15,
        WIRE,
        homepage="https://www.dw.com/en/",
    ),
    seed(
        "france24_en",
        "France 24 English",
        "France Médias Monde",
        N,
        "https://www.france24.com/en/rss",
        B,
        15,
        WIRE,
        homepage="https://www.france24.com/en/",
    ),
    seed(
        "aljazeera_en",
        "Al Jazeera English",
        "Al Jazeera Media Network",
        N,
        "https://www.aljazeera.com/xml/rss/all.xml",
        B,
        15,
        WIRE,
        homepage="https://www.aljazeera.com/",
    ),
    seed(
        "guardian_world",
        "The Guardian World",
        "Guardian Media Group",
        N,
        "https://www.theguardian.com/world/rss",
        C,
        15,
        PRESS,
        homepage="https://www.theguardian.com/world",
    ),
    seed(
        "lemonde_en",
        "Le Monde in English",
        "Le Monde",
        N,
        "https://www.lemonde.fr/en/rss/une.xml",
        C,
        30,
        PRESS,
        homepage="https://www.lemonde.fr/en/",
    ),
    seed(
        "scmp_news",
        "South China Morning Post",
        "SCMP",
        N,
        "https://www.scmp.com/rss/91/feed",
        C,
        30,
        PRESS,
        homepage="https://www.scmp.com/",
    ),
    seed(
        "nikkei_asia",
        "Nikkei Asia",
        "Nikkei",
        N,
        "https://asia.nikkei.com/rss/feed/nar",
        C,
        30,
        PRESS,
        homepage="https://asia.nikkei.com/",
    ),
    seed(
        "times_of_israel",
        "The Times of Israel",
        "The Times of Israel",
        N,
        "https://www.timesofisrael.com/feed/",
        C,
        15,
        PRESS,
        homepage="https://www.timesofisrael.com/",
    ),
    seed(
        "anadolu_en",
        "Anadolu Agency English",
        "Anadolu Agency",
        N,
        "https://www.aa.com.tr/en/rss/default?cat=guncel",
        C,
        15,
        PRESS,
        homepage="https://www.aa.com.tr/en",
    ),
    seed(
        "dawn",
        "Dawn",
        "Dawn Media Group",
        N,
        "https://www.dawn.com/feeds/home",
        C,
        30,
        PRESS,
        homepage="https://www.dawn.com/",
    ),
    seed(
        "meduza_en",
        "Meduza in English",
        "Meduza",
        N,
        "https://meduza.io/rss/en/all",
        C,
        30,
        PRESS,
        homepage="https://meduza.io/en",
    ),
    seed(
        "pravda_ua_en",
        "Ukrainska Pravda in English",
        "Ukrainska Pravda",
        N,
        "https://www.pravda.com.ua/eng/rss/",
        C,
        15,
        PRESS,
        homepage="https://www.pravda.com.ua/eng/",
    ),
    seed(
        "tass_en",
        "TASS English",
        "TASS",
        N,
        "https://tass.com/rss/v2.xml",
        C,
        30,
        STATE_MEDIA,
        homepage="https://tass.com/",
        flags=frozenset({"state_controlled"}),
    ),
)
