"""Official and institutional feeds, verified live on 5 September 2026."""

from __future__ import annotations

from ase.adapters.feeds.rss import RssOptions
from ase.adapters.feeds.rss_seeds import (
    ADVISORY,
    OFFICIAL,
    OGL,
    US_ADVISORY,
    A,
    B,
    H,
    N,
    P,
    RssSeed,
    seed,
)
from ase.domain.events import Credibility

OFFICIAL_SEEDS: tuple[RssSeed, ...] = (
    seed(
        "gov_uk_fcdo_news",
        "GOV.UK FCDO news",
        "Foreign, Commonwealth and Development Office",
        P,
        "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office.atom",
        B,
        30,
        OFFICIAL,
        homepage="https://www.gov.uk/government/organisations/foreign-commonwealth-development-office",
        licence_note=OGL,
    ),
    seed(
        "gov_uk_travel_advice",
        "GOV.UK foreign travel advice",
        "Foreign, Commonwealth and Development Office",
        P,
        "https://www.gov.uk/foreign-travel-advice.atom",
        A,
        30,
        ADVISORY,
        homepage="https://www.gov.uk/foreign-travel-advice",
        licence_note=OGL,
    ),
    seed(
        "us_state_travel_advisories",
        "US State Department travel advisories",
        "US Department of State",
        P,
        "https://travel.state.gov/_res/rss/TAsTWs.xml",
        A,
        60,
        US_ADVISORY,
        homepage="https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories.html",
        licence_note="US Government work",
    ),
    seed(
        "un_news",
        "UN News",
        "United Nations",
        N,
        "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        B,
        30,
        RssOptions(
            tags=frozenset({"un"}),
            credibility=Credibility.PROBABLY_TRUE,
            rationale="UN news service report",
        ),
        homepage="https://news.un.org/",
        licence_note="UN terms of use",
    ),
    seed(
        "un_press",
        "UN press releases and meetings coverage",
        "United Nations",
        P,
        "https://press.un.org/en/rss.xml",
        B,
        30,
        OFFICIAL,
        homepage="https://press.un.org/",
        licence_note="UN terms of use",
    ),
    seed(
        "reliefweb_updates",
        "ReliefWeb updates",
        "UN OCHA ReliefWeb",
        H,
        "https://reliefweb.int/updates/rss.xml",
        B,
        30,
        RssOptions(
            subtype="report",
            tags=frozenset({"humanitarian"}),
            credibility=Credibility.PROBABLY_TRUE,
            rationale="Humanitarian report republished by ReliefWeb; source named in the item",
        ),
        homepage="https://reliefweb.int/",
        licence_note="Site CC BY 4.0; reports keep source copyright",
    ),
    seed(
        "crisis_group",
        "International Crisis Group",
        "International Crisis Group",
        P,
        "https://www.crisisgroup.org/rss",
        B,
        60,
        RssOptions(
            subtype="analysis",
            tags=frozenset({"analysis"}),
            credibility=Credibility.PROBABLY_TRUE,
            rationale="Analysis by an established conflict-prevention organisation",
        ),
        homepage="https://www.crisisgroup.org/",
    ),
)
