"""UK national and regional publisher feeds, verified 13 September 2026."""

from ase.adapters.feeds.rss_news_seed import PERSONAL_TERMS, news_seed
from ase.adapters.feeds.rss_seeds import RssSeed

UK_NEWS_SEEDS: tuple[RssSeed, ...] = (
    news_seed(
        "bbc_uk",
        "BBC News UK",
        "BBC",
        "https://feeds.bbci.co.uk/news/uk/rss.xml",
        "https://www.bbc.co.uk/news/uk",
        "UK national news.",
    ),
    news_seed(
        "sky_uk",
        "Sky News UK",
        "Sky Group",
        "https://feeds.skynews.com/feeds/rss/uk.xml",
        "https://news.sky.com/uk",
        "UK national news.",
    ),
    news_seed(
        "guardian_uk",
        "The Guardian UK news",
        "Guardian Media Group",
        "https://www.theguardian.com/uk-news/rss",
        "https://www.theguardian.com/uk-news",
        "UK national news.",
    ),
    news_seed(
        "independent_uk",
        "The Independent UK",
        "Independent Digital News and Media",
        "https://www.independent.co.uk/news/uk/rss",
        "https://www.independent.co.uk/news/uk",
        "UK national news.",
        terms=PERSONAL_TERMS,
    ),
    news_seed(
        "stv_scotland",
        "STV News Scotland",
        "STV Group",
        "https://news.stv.tv/feed",
        "https://news.stv.tv/",
        "Scottish national and regional news.",
    ),
    news_seed(
        "bbc_scotland",
        "BBC News Scotland",
        "BBC",
        "https://feeds.bbci.co.uk/news/scotland/rss.xml",
        "https://www.bbc.co.uk/news/scotland",
        "Scottish national and regional news.",
    ),
    news_seed(
        "bbc_wales",
        "BBC News Wales",
        "BBC",
        "https://feeds.bbci.co.uk/news/wales/rss.xml",
        "https://www.bbc.co.uk/news/wales",
        "Welsh national and regional news.",
    ),
    news_seed(
        "bbc_northern_ireland",
        "BBC News Northern Ireland",
        "BBC",
        "https://feeds.bbci.co.uk/news/northern_ireland/rss.xml",
        "https://www.bbc.co.uk/news/northern_ireland",
        "Northern Ireland news.",
    ),
    news_seed(
        "herald_scotland",
        "The Herald Scotland",
        "Newsquest",
        "https://www.heraldscotland.com/news/homenews/rss/",
        "https://www.heraldscotland.com/",
        "Scottish national and regional news.",
    ),
    news_seed(
        "wales_online",
        "WalesOnline",
        "Reach plc",
        "https://www.walesonline.co.uk/news/?service=rss",
        "https://www.walesonline.co.uk/news/",
        "Welsh national and regional news.",
    ),
    news_seed(
        "belfast_live",
        "BelfastLive",
        "Reach plc",
        "https://www.belfastlive.co.uk/news/?service=rss",
        "https://www.belfastlive.co.uk/news/",
        "Belfast and Northern Ireland news.",
    ),
    news_seed(
        "manchester_evening",
        "Manchester Evening News",
        "Reach plc",
        "https://www.manchestereveningnews.co.uk/news/?service=rss",
        "https://www.manchestereveningnews.co.uk/news/",
        "Greater Manchester regional news.",
    ),
    news_seed(
        "birmingham_live",
        "BirminghamLive",
        "Reach plc",
        "https://www.birminghammail.co.uk/news/?service=rss",
        "https://www.birminghammail.co.uk/news/",
        "Birmingham and West Midlands regional news.",
    ),
    news_seed(
        "northern_echo",
        "The Northern Echo",
        "Newsquest",
        "https://www.thenorthernecho.co.uk/news/rss/",
        "https://www.thenorthernecho.co.uk/news/",
        "North East England regional news.",
    ),
)
