"""Official and institutional feeds, verified live on 5 and 13 September 2026.

The Kremlin, US State Department, Chinese MFA and BelTA English feeds were tried on
13 September 2026 and left out: the Kremlin feed is served only over plain HTTP
(its TLS handshake fails), State returns 407, and the others return HTML or 403.
"""

from __future__ import annotations

from ase.adapters.feeds.rss import RssOptions
from ase.adapters.feeds.rss_seeds import (
    ADVISORY,
    OFFICIAL,
    OGL,
    US_ADVISORY,
    A,
    B,
    C,
    H,
    N,
    P,
    RssSeed,
    seed,
)
from ase.domain.events import Credibility

STATE_OFFICIAL = RssOptions(
    subtype="statement",
    tags=frozenset({"official", "state_controlled"}),
    credibility=Credibility.DOUBTFUL,
    rationale="Official release of a state with controlled media; treat as its position",
)

OFFICIAL_SEEDS: tuple[RssSeed, ...] = (
    seed(
        "gov_uk_fcdo_news",
        "GOV.UK FCDO news",
        "Foreign, Commonwealth and Development Office",
        P,
        "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office.atom",
        B,
        30,
        OFFICIAL,
        homepage="https://www.gov.uk/government/organisations/foreign-commonwealth-development-office",
        licence_note=OGL,
    ),
    seed(
        "gov_uk_travel_advice",
        "GOV.UK foreign travel advice",
        "Foreign, Commonwealth and Development Office",
        P,
        "https://www.gov.uk/foreign-travel-advice.atom",
        A,
        30,
        ADVISORY,
        homepage="https://www.gov.uk/foreign-travel-advice",
        licence_note=OGL,
    ),
    seed(
        "gov_uk_mod_news",
        "GOV.UK Ministry of Defence news",
        "Ministry of Defence",
        P,
        "https://www.gov.uk/government/organisations/ministry-of-defence.atom",
        B,
        30,
        OFFICIAL,
        homepage="https://www.gov.uk/government/organisations/ministry-of-defence",
        licence_note=OGL,
    ),
    seed(
        "gov_uk_number_10",
        "GOV.UK Prime Minister's Office news",
        "Prime Minister's Office, 10 Downing Street",
        P,
        "https://www.gov.uk/government/organisations/prime-ministers-office-10-downing-street.atom",
        B,
        30,
        OFFICIAL,
        homepage="https://www.gov.uk/government/organisations/prime-ministers-office-10-downing-street",
        licence_note=OGL,
    ),
    seed(
        "gov_uk_home_office",
        "GOV.UK Home Office news",
        "Home Office",
        P,
        "https://www.gov.uk/government/organisations/home-office.atom",
        B,
        30,
        OFFICIAL,
        homepage="https://www.gov.uk/government/organisations/home-office",
        licence_note=OGL,
    ),
    seed(
        "whitehouse_news",
        "White House news",
        "The White House",
        P,
        "https://www.whitehouse.gov/news/feed/",
        B,
        30,
        OFFICIAL,
        homepage="https://www.whitehouse.gov/news/",
        licence_note="US Government work",
    ),
    seed(
        "us_dod_news",
        "US Department of Defense news",
        "US Department of Defense",
        P,
        "https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945&max=10",
        B,
        30,
        OFFICIAL,
        homepage="https://www.defense.gov/News/",
        licence_note="US Government work",
    ),
    seed(
        "russia_mfa_ru",
        "Russian MFA news (Russian)",
        "Ministry of Foreign Affairs of the Russian Federation",
        P,
        "https://mid.ru/ru/rss/",
        C,
        30,
        STATE_OFFICIAL,
        homepage="https://mid.ru/ru/",
        language="ru",
        licence_note="Ministry terms; titles and links only",
        flags=frozenset({"state_controlled"}),
    ),
    seed(
        "us_state_travel_advisories",
        "US State Department travel advisories",
        "US Department of State",
        P,
        "https://travel.state.gov/_res/rss/TAsTWs.xml",
        A,
        60,
        US_ADVISORY,
        homepage="https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories.html",
        licence_note="US Government work",
    ),
    seed(
        "un_news",
        "UN News",
        "United Nations",
        N,
        "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        B,
        30,
        RssOptions(
            tags=frozenset({"un"}),
            credibility=Credibility.PROBABLY_TRUE,
            rationale="UN news service report",
        ),
        homepage="https://news.un.org/",
        licence_note="UN terms of use",
    ),
    seed(
        "un_press",
        "UN press releases and meetings coverage",
        "United Nations",
        P,
        "https://press.un.org/en/rss.xml",
        B,
        30,
        OFFICIAL,
        homepage="https://press.un.org/",
        licence_note="UN terms of use",
    ),
    seed(
        "reliefweb_updates",
        "ReliefWeb updates",
        "UN OCHA ReliefWeb",
        H,
        "https://reliefweb.int/updates/rss.xml",
        B,
        30,
        RssOptions(
            subtype="report",
            tags=frozenset({"humanitarian"}),
            credibility=Credibility.PROBABLY_TRUE,
            rationale="Humanitarian report republished by ReliefWeb; source named in the item",
        ),
        homepage="https://reliefweb.int/",
        licence_note="Site CC BY 4.0; reports keep source copyright",
    ),
    seed(
        "crisis_group",
        "International Crisis Group",
        "International Crisis Group",
        P,
        "https://www.crisisgroup.org/rss",
        B,
        60,
        RssOptions(
            subtype="analysis",
            tags=frozenset({"analysis"}),
            credibility=Credibility.PROBABLY_TRUE,
            rationale="Analysis by an established conflict-prevention organisation",
        ),
        homepage="https://www.crisisgroup.org/",
    ),
)
